### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by Maitreya229** [LAMDA-NJU/Deep-Forest#113]
Dear Sir,

I have 32 inputs and output 2 numbers (0, 1).

The same data works fine with gcForest,
But when using Deep-Forest, the following error message appears：
**Traceback (most recent call last):
  File "test_openface.py", line 124, in <module>
    model.fit(X_train, Y_train)
  File "C:\ProgramData\Anaconda3\envs\deepForest\lib\site-packages\deepforest\cascade.py", line 1397, in fit
    super().fit(X, y, sample_weight)
  File "C:\ProgramData\Anaconda3\envs\deepForest\lib\site-packages\deepforest\cascade.py", line 744, in fit
    self._check_input(X, y)
  File "C:\ProgramData\Anaconda3\envs\deepForest\lib\site-packages\deepforest\cascade.py", line 633, in _check_input
    _, self.n_features_ = X.shape
ValueError: too many values to unpack (expected 2)**

1. Please how can I solve this problem?
2. When creating CascadeForestClassifier(), what parameters need to be set more appropriate? 

Thank you.

**Comment by xuyxu** [comment]
Hi @Maitreya229, could you show me the source code of `test_openface.py`

**Comment by xuyxu** [comment]
Closed due to inactivity. Please reopen it if you could provide more information.
