### ISSUE TITLE
cant import CascadeForestRegressor

### ISSUE THREAD

**Issue by trainma** [LAMDA-NJU/Deep-Forest#118]
Traceback (most recent call last):
  File "E:\Conda\lib\site-packages\IPython\core\interactiveshell.py", line 3369, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-80de5b0e023f>", line 1, in <cell line: 1>
    from deepforest import CascadeForestRegressor
  File "C:\Users\a1034\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\222.4167.29.plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\a1034\AppData\Roaming\Python\Python39\site-packages\deepforest\__init__.py", line 1, in <module>
    from .cascade import CascadeForestClassifier, CascadeForestRegressor
  File "C:\Users\a1034\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\222.4167.29.plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\a1034\AppData\Roaming\Python\Python39\site-packages\deepforest\cascade.py", line 21, in <module>
    from . import _io, _utils
  File "C:\Users\a1034\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\222.4167.29.plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\a1034\AppData\Roaming\Python\Python39\site-packages\deepforest\_utils.py", line 7, in <module>
    from . import _cutils as _LIB
  File "C:\Users\a1034\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\222.4167.29.plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "deepforest\_cutils.pyx", line 1, in init deepforest._cutils
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
-------------------------------------------------------------------------------
Hi, my numpy version is 1.20,what is the true version of numpy?

**Comment by xuyxu** [comment]
Closed due to inactivity.
