### ISSUE TITLE
Unable to import CascadeForestClassifier

### ISSUE THREAD

**Issue by tomthecat1** [LAMDA-NJU/Deep-Forest#131]
Despite following the instructions provided in the README document and using pip to install 'deep-forest,' I encountered a 'ModuleNotFoundError' when trying to import the package in my code.
 
To troubleshoot, I attempted to clone the GitHub repository directly and forced the environment to recognize the cloned path. Unfortunately, this resulted in another error: 'ImportError: cannot import name '_cutils' from partially initialized module 'deepforest' (most likely due to a circular import) (/content/Deep-Forest/deepforest/init.py).'

This is the full error message:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-27-f4d01d641d79> in <cell line: 1>()
----> 1 from deepforest.cascade import CascadeForestClassifier

2 frames
/content/Deep-Forest/deepforest/_utils.py in <module>
      5 from datetime import datetime
      6 
----> 7 from . import _cutils as _LIB
      8 
      9 

ImportError: cannot import name '_cutils' from partially initialized module 'deepforest' (most likely due to a circular import) (/content/Deep-Forest/deepforest/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by XiaoYigao** [comment]
I also have this problem, how should I solve it?

**Comment by 0313Fly** [comment]
> Hi @tomthecat1, I have sent you an email to solve this issue. Feel free to comment below if you have any other problem.

I also have this problem, could you please email to me?Thanks very much.
My email: 863163094@qq.com

**Comment by ipap0123** [comment]
Hi @xuyxu, I have the same issue when trying to run the python code in Windows. Can you please send me the solution for this issue?

**Comment by RaXie0101** [comment]
Hi @xuyxu , I have the same issue when trying to run the python code. Can you please send me the solution for this issue?

**Comment by RaXie0101** [comment]
Hi @xuyxu , I have the same issue when trying to run the python code. Can you please send me the solution for this issue?My email: 913990918@qq.com

**Comment by xsyshr** [comment]
Hi @xuyxu , I have the same issue when trying to run the python code. Can you please send me the solution for this issue? My email: xusiyang1227@163.com

**Comment by zhuyongWillem** [comment]
@xuyxu 我也遇见了这个问题，可以发一下怎么解决的吗？邮箱yong_zzhu@163.com

**Comment by MichaelTan2016** [comment]
@xuyxu 同求，邮箱tansx2016@126.com

**Comment by Mitesh-web** [comment]
While installing deep-forest using pip intall . the error says  "Getting requirements to build wheel did not run successfully."
Would like a solution for this. Currently running python 3.12 on windows and have installed the repository manually.
This is the complete error message:

(new_env) C:\Users\mites\Deep-Forest>pip install .
Processing c:\users\mites\deep-forest
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\mites\Deep-Forest\new_env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\mites\Deep-Forest\new_env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mites\Deep-Forest\new_env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:\Users\mites\Deep-Forest\new_env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python312\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\mites\AppData\Local\Temp\pip-build-env-jy24x6aj\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\mites\AppData\Local\Temp\pip-build-env-jy24x6aj\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\mites\AppData\Local\Temp\pip-build-env-jy24x6aj\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

(new_env) C:\Users\mites\Deep-Forest>python -c "from deepforest import CascadeForestClassifier; print(CascadeForestClassifier)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\mites\Deep-Forest\deepforest\__init__.py", line 1, in <module>
    from .cascade import CascadeForestClassifier, CascadeForestRegressor
  File "C:\Users\mites\Deep-Forest\deepforest\cascade.py", line 21, in <module>
    from . import _io, _utils
  File "C:\Users\mites\Deep-Forest\deepforest\_utils.py", line 7, in <module>
    from . import _cutils as _LIB
ImportError: cannot import name '_cutils' from partially initialized module 'deepforest' (most likely due to a circular import) (C:\Users\mites\Deep-Forest\deepforest\__init__.py)

(new_env) C:\Users\mites\Deep-Forest>pip uninstall setuptools
Found existing installation: setuptools 74.1.2
Uninstalling setuptools-74.1.2:
  Would remove:
    c:\users\mites\deep-forest\new_env\lib\site-packages\_distutils_hack\*
    c:\users\mites\deep-forest\new_env\lib\site-packages\distutils-precedence.pth
    c:\users\mites\deep-forest\new_env\lib\site-packages\pkg_resources\*
    c:\users\mites\deep-forest\new_env\lib\site-packages\setuptools-74.1.2.dist-info\*
    c:\users\mites\deep-forest\new_env\lib\site-packages\setuptools\*
Proceed (Y/n)? pip install setuptools
Your response ('pip install setuptools') was not one of the expected responses: y, n,
Proceed (Y/n)? y
  Successfully uninstalled setuptools-74.1.2

(new_env) C:\Users\mites\Deep-Forest>pip install setuptools
Collecting setuptools
  Using cached setuptools-74.1.2-py3-none-any.whl.metadata (6.7 kB)
Using cached setuptools-74.1.2-py3-none-any.whl (1.3 MB)
Installing collected packages: setuptools
Successfully installed setuptools-74.1.2

(new_env) C:\Users\mites\Deep-Forest>pip update setuptools
ERROR: unknown command "update"

(new_env) C:\Users\mites\Deep-Forest>pip install .
Processing c:\users\mites\deep-forest
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\mites\Deep-Forest\new_env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\mites\Deep-Forest\new_env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mites\Deep-Forest\new_env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:\Users\mites\Deep-Forest\new_env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python312\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\mites\AppData\Local\Temp\pip-build-env-2wm0rxmk\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\mites\AppData\Local\Temp\pip-build-env-2wm0rxmk\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\mites\AppData\Local\Temp\pip-build-env-2wm0rxmk\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by kjdsfbchkadwbcuiwbcfiw** [comment]
Hi  @xuyxu, I have the same issue when trying to run the python code in Windows. Can you please send me the solution for this issue?

**Comment by nwu-ljz** [comment]
> 您好，我已经向您发送了一封电子邮件来解决此问题。如果您有任何其他问题，请随时在下面发表评论。
我也遇到了同样的问题能给我发一封邮件吗
