### ISSUE TITLE
导入出现错误

### ISSUE THREAD

**Issue by XiaoYigao** [LAMDA-NJU/Deep-Forest#132]
遵循安装过程，但是出现以下错误：
Traceback (most recent call last):
  File "F:\Deep-Forest-master\鸢尾花.py", line 5, in <module>
    from deepforest import CascadeForestClassifier
  File "F:\Deep-Forest-master\deepforest\__init__.py", line 1, in <module>
    from .cascade import CascadeForestClassifier, CascadeForestRegressor
  File "F:\Deep-Forest-master\deepforest\cascade.py", line 21, in <module>
    from . import _io, _utils
  File "F:\Deep-Forest-master\deepforest\_utils.py", line 7, in <module>
    from . import _cutils as _LIB
ImportError: cannot import name '_cutils' from partially initialized module 'deepforest' (most likely due to a circular import) (F:\Deep-Forest-master\deepforest\__init__.py)
这样应该如何解决？

**Comment by DamarisDeng** [comment]
遇到了一样的问题
