### ISSUE TITLE
gpu support and sklearn support

### ISSUE THREAD

**Issue by BinchaoPeng** [LAMDA-NJU/Deep-Forest#91]
请问现在可以支持gpu了吗?另外是否支持sklearn的gridSearchCV呢？

**Comment by IncubatorShokuhou** [comment]
@BinchaoPeng 可以自定义estimators和predictor，然后使用支持gpu的评估器作为estimator和predictor

**Comment by IncubatorShokuhou** [comment]
另外，如果你不自定义estimator和predictor的话，cv应该是没问题的。但是如果你[用了customized estimators](https://deep-forest.readthedocs.io/en/stable/advanced_topics/use_customized_estimator.html)的话，那就会出bug了，因为cv里面会用到`sklearn.base.clone` (见https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/model_selection/_search.py#L769)

**Comment by BinchaoPeng** [comment]
确实，`GridSearchCV`是没有问题的，至于自定义，不知道你们有带有gpu版本的demo吗？看过了文档感觉还是不知道如何下手。

**Comment by xuyxu** [comment]
感谢 @IncubatorShokuhou 的说明。关于使用GPU，可以考虑使用cuml中的随机森林：https://docs.rapids.ai/api/cuml/stable/api.html#random-forest

**Comment by BinchaoPeng** [comment]
好的，谢谢，我去看看

**Comment by xuyxu** [comment]
如果准备尝试的话，十分欢迎您在这个issue下面进行反馈 ;-)

**Comment by BinchaoPeng** [comment]
恩恩，好的，希望这个project可以实现gpu支持和sklearn支持

**Comment by BinchaoPeng** [comment]
还是报错了，关于`GridSearchCV`的：
```python
/home/pbc/anaconda3/envs/cuda9/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
[CV 1/5] END predictor=xgboost; accuracy: (test=nan) average_precision: (test=nan) f1: (test=nan) roc_auc: (test=nan) total time=10.0min
  File "/home/pbc/anaconda3/envs/cuda9/lib/python3.6/site-packages/sklearn/metrics/_scorer.py", line 56, in _cached_call
    return cache[method]
KeyError: 'decision_function'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/pbc/anaconda3/envs/cuda9/lib/python3.6/site-packages/sklearn/metrics/_scorer.py", line 334, in _score
    y_pred = method_caller(clf, "decision_function", X)
  File "/home/pbc/anaconda3/envs/cuda9/lib/python3.6/site-packages/sklearn/metrics/_scorer.py", line 58, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'CascadeForestClassifier' object has no attribute 'decision_function'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/pbc/anaconda3/envs/cuda9/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 687, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/home/pbc/anaconda3/envs/cuda9/lib/python3.6/site-packages/sklearn/metrics/_scorer.py", line 88, in __call__
    *args, **kwargs)
  File "/home/pbc/anaconda3/envs/cuda9/lib/python3.6/site-packages/sklearn/metrics/_scorer.py", line 353, in _score
    y_pred = self._select_proba_binary(y_pred, clf.classes_)
AttributeError: 'CascadeForestClassifier' object has no attribute 'classes_'
  UserWarning,
```

**Comment by xuyxu** [comment]
好的，我周末研究一下。

**Comment by BinchaoPeng** [comment]
(class_)[https://blog.csdn.net/cxx654/article/details/106727812/]
(decision_funtion)[https://blog.csdn.net/u014765410/article/details/82924377?utm_medium=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7EBlogCommendFromMachineLearnPai2%7Edefault-1.control&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7EBlogCommendFromMachineLearnPai2%7Edefault-1.control]
这两个链接或许有用

**Comment by BinchaoPeng** [comment]
> 好的，我周末研究一下。

请问你搞定了吗？发现不结合网格搜索和交叉验证这两个功能，不好实用，建议还是接入sklearn比较好

**Comment by py666888** [comment]
请问不自定义分类器，现在支持网格搜索调参吗？

**Comment by BinchaoPeng** [comment]
> 请问不自定义分类器，现在支持网格搜索调参吗？

需要自己实现，不支持sklearn，按照sklearn的方式实现就可以了
